### PR TITLE
[PR] Featured image information button

### LINKED ISSUE #112: Add information button to feature images
Need to have captions and credits for our feature images. We'll use an "i" button for information, synced to the season of the issue.
See attached. I have svgs for the icon.

[web_photo-info.pdf](https://github.com/washingtonstateuniversity/magazine.wsu.edu/files/203482/web_photo-info.pdf)

### PR DESCRIPTION
**Pull request by philcable**
Fixes #112 @jeremyfelt #reviewmerge?

### CODE REVIEW

**Comment by philcable** [comment]
Let's hold off on this until after we've had some time to brainstorm lightbox solutions.

**Comment by wsmagazine** [comment]
Do we have a lightbox solution for WSU-WP? Bickelhaupt is using a lightbox for a magazine project.

**Comment by jeremyfelt** [comment]
We used [Fluidbox](https://github.com/terrymun/Fluidbox) at some point when prepping for the COB site in our [toolbox demo](https://github.com/washingtonstateuniversity/toolbox-demo). That appears to be [applied to gallery items](https://github.com/washingtonstateuniversity/business.wsu.edu/blob/619f1ed60777df69a32858738f064c015a781ed2/js/custom.js) on business.wsu.edu now, though it's been a while so I'm not sure where to verify. :)

[Colorbox](https://github.com/jackmoore/colorbox) is also available pretty easily on the platform by checking the box in the custom JavaScript editor.

@jbickelhaupt what solution are you looking at?

**Comment by philcable** [comment]
Last we talked about it, @jbickelhaupt was using Colorbox. In the interest of time, I can go back to using it for this feature.

As for implementation, what makes the most sense? Should we use the custom JavaScript editor, or - considering issue #121 - should we queue up our own copy of Colorbox (preferably, only when needed)?

**Comment by jeremyfelt** [comment]
> As for implementation, what makes the most sense? Should we use the custom JavaScript editor, or - considering issue #121 - should we queue up our own copy of Colorbox (preferably, only when needed)?

Let's go with our own. There's a better chance we use an updated version. :)

**Comment by jbickelhaupt** [comment]
@jeremyfelt, Phil is correct. I'm using Colorbox and pulling it up just like I did on that international map for College of Ed. Will get the styles and scripts rolled into the child theme before the web extra feature I'm working on launches.

**Comment by philcable** [comment]
I'm closing this branch in favor of https://github.com/washingtonstateuniversity/magazine.wsu.edu/pull/129, which piggybacks off of the recently merged colorbox additions.

**Pull request closed without merging**
